appiumURL=http://127.0.0.1:4723/
androidAutomationName=UiAutomator2
androidAppLocation=/app/Ida-staging-debug
androidAppPackage=org.intelehealth.app
androidAppActivity=org.intelehealth.app.ui.splash.activity.SplashActivity